[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization"
    Access-Control-Allow-Methods = "GET,DELETE,PATCH,POST,PUT,OPTIONS"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
